<div id="block_notice_license" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('License'); ?>">
    <?php
    $email = '<a href="mailto:support@m2epro.com">support@m2epro.com</a>';

    $components = '';

    $ebayText = '';
    if (isset($this->components[Ess_M2ePro_Helper_Component_Ebay::NICK])) {
        $ebayText = Mage::helper('M2ePro')->__(
            'The <span style="text-decoration: underline;">eBay component</span>, its upgrades and support are free according to eBay / Magento Partner Agreement. And they will stay free until the partner agreement is active.<br/>'
        );
        $components .= '<span style="text-decoration: underline;">eBay</span>';
    }

    $amazonText = '';
    if (isset($this->components[Ess_M2ePro_Helper_Component_Amazon::NICK])) {
        $amazonText = Mage::helper('M2ePro')->__(
            'The current <span style="text-decoration: underline;">Amazon component</span> is in <span style="text-decoration: underline;">Beta</span> state and is provided free of charge. However, please be advised that upon the live version of the product release some monthly subscription fee will be introduced.</br>'
        );
        $components == '' || $components .= ' and ';
        $components .= '<span style="text-decoration: underline;">Amazon</span>';
    }

    $components .= ' component';
    if (count($this->components) > 1) {
        $components .= 's';
    }

    $tempString = Mage::helper('M2ePro')->__('<br/><b>Note:</b> M2E Pro v.4.x.x consists of %components%.<br/>
    %ebayText%
    %amazonText%
    <br>
    <hr style="color:#D6D6D6"/><br/>
    M2E Pro extension requires activation for its work.<br/><br/>
    To get the License Key, click the <span style="text-decoration: underline;">Get License Key</span> link and follow the instructions.<br/>
    When you got your License Key, press the <span style="text-decoration: underline;">Enter</span> button
    and enter your License Key in appeared text field. Press the <span style="text-decoration: underline;">Confirm</span> button.<br/><br/>
    <b>Note:</b> If you have not received the License Key, please contact us right away at %email%.');
    echo str_replace(
        array('%email%','%components%','%ebayText%','%amazonText%'),
        array($email,$components,$ebayText,$amazonText),
        $tempString);
    ?>
</div>

<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/adminhtml_license/save'); ?>';
    M2ePro.url.checkLicense = '<?php echo $this->getUrl('*/adminhtml_license/checkLicense'); ?>';

    M2ePro.text.license_validation_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You must get valid Trial or Live license key.')); ?>';

    Event.observe(window, 'load', function() {
        LicenseHandlerObj = new LicenseHandler();
        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_license_data" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('License Data'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('License Key'); ?>: </label>
                            </td>
                            <td id="license_text_key_container" class="value">
                                <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                    <span style="display: block; padding: 4px 0 0;">
                                <?php } ?>

                                <?php echo $this->key; ?>
                                <?php if ($this->key == '') { echo $this->getChildHtml('enter_key'); } ?>
                                &nbsp;&nbsp;

                                <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                    </span>
                                <?php } ?>
                            </td>
                            <td id="license_input_key_container" class="value" style="display: none;">
                                <input id="key" name="key" value="<?php echo $this->escapeHtml($this->key); ?>" type="text" class="input-text required-entry" />
                                &nbsp;&nbsp;
                            </td>
                            <td id="change_license_key_container" class="value" <?php if($this->key == '') { ?>style="display: none;"<?php } ?>>
                                <?php echo $this->getChildHtml('change_key'); ?>
                                &nbsp;
                                <?php echo $this->getChildHtml('refresh_status'); ?>
                            </td>
                            <td id="confirm_license_key_container" class="value" style="display: none;">
                                <?php echo $this->getChildHtml('confirm_key'); ?>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"></td>
                            <td class="value">
                                <a href="https://m2epro.com/clients/" target="_blank"><?php echo Mage::helper('M2ePro')->__('Get License Key'); ?></a>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

    <?php if ($this->valid['domain'] != '' || $this->valid['ip'] != '' || $this->valid['directory'] != '') { ?>

        <div class="entry-edit" id="magento_block_license_valid" collapseable="no">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('License Validation'); ?></h4>
            </div>

            <div class="fieldset">
                <div class="hor-scroll">

                    <table class="form-list" cellspacing="0" cellpadding="0">

                        <colgroup class="label"></colgroup>
                        <colgroup class="value"></colgroup>

                        <tbody>

                            <?php if ($this->valid['domain'] != '') { ?>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('Domain'); ?>: </label>
                                    </td>
                                    <td class="value">
                                        <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                            <span style="display: block; padding: 4px 0 0;">
                                        <?php } ?>

                                        <?php echo $this->valid['domain']; ?>

                                        <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                            </span>
                                        <?php } ?>
                                    </td>
                                </tr>

                            <?php } ?>

                            <?php if ($this->valid['ip'] != '') { ?>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('IP'); ?>: </label>
                                    </td>
                                    <td class="value">
                                        <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                            <span style="display: block; padding: 4px 0 0;">
                                        <?php } ?>

                                        <?php echo $this->valid['ip']; ?>

                                        <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                            </span>
                                        <?php } ?>
                                    </td>
                                </tr>

                            <?php } ?>

                            <?php if ($this->valid['directory'] != '') { ?>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('Directory'); ?>: </label>
                                    </td>
                                    <td class="value">
                                        <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                            <span style="display: block; padding: 4px 0 0;">
                                        <?php } ?>

                                        <?php echo $this->valid['directory']; ?>

                                        <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                            </span>
                                        <?php } ?>
                                    </td>
                                </tr>

                            <?php } ?>

                        </tbody>

                    </table>

                </div>
            </div>

        </div>

    <?php } ?>

    <?php if ($this->key != '') { ?>

        <?php foreach ($this->components as $componentName => $componentData) { ?>

            <div class="entry-edit" id="magento_block_license_component_<?php echo strtolower($componentName); ?>" collapseable="no">

                <div class="entry-edit-head">

                    <?php
                        $componentTitle = '';
                        switch ($componentName) {
                            case Ess_M2ePro_Helper_Component_Ebay::NICK:
                                $componentTitle = Ess_M2ePro_Helper_Component_Ebay::TITLE;
                                break;
                            case Ess_M2ePro_Helper_Component_Amazon::NICK:
                                $componentTitle = Ess_M2ePro_Helper_Component_Amazon::TITLE;
                                break;
                        }
                    ?>

                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $componentTitle.' '.Mage::helper('M2ePro')->__('Access'); ?></h4>
                </div>

                <div class="fieldset">
                    <div class="hor-scroll">

                        <?php if ($componentName == Ess_M2ePro_Helper_Component_Ebay::NICK) { ?>
                            <div id="block_notice_license_ebay" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
                                <?php echo Mage::helper('M2ePro')->__('<b>Note:</b> The eBay component, its upgrades and support are free according to eBay / Magento Partner Agreement. And they will stay free
    until the partner agreement is active.'); ?>
                            </div>
                        <?php } ?>

                        <?php if ($componentName == Ess_M2ePro_Helper_Component_Amazon::NICK) { ?>
                            <div id="block_notice_license_amazon" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
                                <?php echo Mage::helper('M2ePro')->__('<b>Note:</b> The current Beta version of the Amazon module is provided free of charge.
                                However, please be advised that upon the live version of the product release some monthly subscription fee will be introduced.'); ?>
                            </div>
                        <?php } ?>

                        <table class="form-list" cellspacing="0" cellpadding="0">

                            <colgroup class="label"></colgroup>
                            <colgroup class="value"></colgroup>

                            <tbody>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('Current Status'); ?>: </label>
                                    </td>
                                    <td class="value">
                                        <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                            <span style="display: block; padding: 4px 0 0;">
                                        <?php } ?>

                                        <strong>
                                            <?php if ($componentData['mode'] == Ess_M2ePro_Model_License_Model::MODE_NONE) echo Mage::helper('M2ePro')->__('None License'); ?>
                                            <?php if ($componentData['mode'] == Ess_M2ePro_Model_License_Model::MODE_TRIAL) echo Mage::helper('M2ePro')->__('Trial License'); ?>
                                            <?php if ($componentData['mode'] == Ess_M2ePro_Model_License_Model::MODE_LIVE) echo Mage::helper('M2ePro')->__('Live License'); ?>
                                        </strong>

                                        <?php if ($componentData['mode'] != Ess_M2ePro_Model_License_Model::MODE_NONE &&
                                                 ($componentData['status'] == Ess_M2ePro_Model_License_Model::STATUS_SUSPENDED ||
                                                  $componentData['status'] == Ess_M2ePro_Model_License_Model::STATUS_CLOSED)) { ?>
                                                <span style="color:red;">(
                                                    <?php if ($componentData['status'] == Ess_M2ePro_Model_License_Model::STATUS_SUSPENDED) echo Mage::helper('M2ePro')->__('Suspended'); ?>
                                                    <?php if ($componentData['status'] == Ess_M2ePro_Model_License_Model::STATUS_CLOSED) echo Mage::helper('M2ePro')->__('Closed'); ?>
                                                )</span>
                                        <?php } ?>

                                        <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                            </span>
                                        <?php } ?>
                                    </td>
                                </tr>

                                <?php if ($componentData['mode'] != Ess_M2ePro_Model_License_Model::MODE_NONE) { ?>

                                    <tr>
                                        <td class="label">
                                            <label><?php echo Mage::helper('M2ePro')->__('Expiration Date'); ?>: </label>
                                        </td>
                                        <td class="value">
                                            <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                                <span style="display: block; padding: 4px 0 0;">
                                            <?php } ?>

                                            <?php echo $componentData['expiration_date']; ?>

                                            <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                                </span>
                                            <?php } ?>
                                        </td>
                                    </tr>

                                <?php } ?>

                            </tbody>

                        </table>

                    </div>
                </div>

            </div>

        <?php } ?>

    <?php } ?>

</form>