<?php 
/**
 * ShipStation
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@auctane.com so we can send you a copy immediately.
 *
 * @category   Shipping
 * @package    Auctane_ShipStation
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<table>
<col width="50%" />
<col width="50%" />
<tbody><tr>
	<td><?php echo $this->getChildHtml('linkup') ?></td>
	<td>
		<p><b><?php echo $this->__('Don\'t have a ShipStation account yet?') ?></b></p>
		<p><?php echo $this->__('Please go to %s to select a plan. You can try it for free for 30 days!', '<a href="http://www.shipstation.com/pricing" target="_blank">http://www.shipstation.com/pricing</a>') ?></p>
		<p><?php echo $this->__('Here are some highlights:') ?></p>
		<ol style="list-style: decimal; padding-left: 20px;">
			<li><?php echo $this->__('Consolidate your orders from Magento and other marketplaces such as eBay, Amazon, Buy.com and more.') ?></li>
			<li><?php echo $this->__('Print shipping labels for both USPS and UPS.') ?></li>
			<li><?php echo $this->__('Receive deep discounts on USPS Priority and Express Mail postage.') ?></li>
			<li><?php echo $this->__('Create labels and packing slips in batch.') ?></li>
			<li><?php echo $this->__('Automate your business with order automation rules.') ?></li>
		</ol>
		<br />
		<img src="//app.shipstation.com/images/home-screen-shot.png" />
	</td>
</tr></tbody>
</table>
