<script type="text/javascript">

	var checkoutProducts = [];
	
	<?php foreach (Mage::getSingleton('checkout/session')->getQuote()->getAllVisibleItems() as $item) : ?>
		
		<?php

			$collection = $item->getProduct()->getCategoryIds();
			
			if (!$collection)
			{
				$collection[] = Mage::app()->getStore()->getRootCategoryId();
			}
			
			$category = Mage::getModel('catalog/category')->load
			(
				end($collection)
			);
			
			$options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct());
		?>
		
		checkoutProducts.push(
		{
			'name': 		'<?php echo $item->getName() ?>',
			'category': 	'<?php echo $category->getName() ?>',
			'id': 			'<?php echo $item->getProduct()->getSku() ?>',
			'price': 		'<?php echo $item->getProduct()->getPrice() ?>',
			'brand':		'<?php echo $item->getProduct()->getAttributeText('manufacturer') ?>',
			'quantity': 	'<?php echo $item->getQty() ?>',
			'variant':		'<?php echo $item->getItemId() ?>'
		})
		
	<?php endforeach; ?>


	AEC.getSteps = function(selector)
	{	
		var find = function()
		{
			return document.querySelectorAll('.opc');
		}
			
		var element = find();

		if (element && 1 == element.length)
		{
			return element[0].children;
		}

		return null;
	}

	AEC.getStep = function(section, steps)
	{
		for (i = 0, l = steps.length; i < l; i++)
		{
			if (-1 != steps[i].id.indexOf(section))
			{
				return {
					index: i, 
					step: steps[i]
				}
			}
		}

		return {
			index: -1,
			step: null
		}
	}
	
	
	Checkout.prototype.gotoSection = Checkout.prototype.gotoSection.wrap(function(parentMethod, section, reloadProgressBlock) 
	{
		parentMethod(section, reloadProgressBlock);

		var steps = AEC.getSteps(), step = AEC.getStep(section, steps), index = step.index;
		
		if (-1 !== index)
		{
			/* Track checkout step */
			var data = 
			{
				'event': 'checkout',
				'ecommerce': 
				{
					'checkout': 
					{
						'actionField': 
						{
							'step': ++index
						},
						'products': checkoutProducts
					}
				},
				'eventCallback': function()
				{
					if (AEC.debug)
					{
						console.log('GTM: Fired GTM event - ' + data.event + ' Step: ' + index);
					}
					else return true;
				}
			}

			dataLayer.push(data);
		}		
	});
</script>