<script type="text/javascript">

	EC.push(function(dataLayer)
	{
		var collection = [], ecomm = 
		{
			i:[],
			p:[],
			v:[]
		};

		/* Always push product */
		collection.push(
		{
			'name': 		'<?php echo Mage::helper('core')->jsQuoteEscape($this->getProduct()->getName()) ?>',
			'id': 		    '<?php echo $this->getProduct()->getSku() ?>',
			'price': 		'<?php echo $this->getProduct()->getFinalPrice() ?>',
			'variant':		'<?php echo $this->getProduct()->getResource()->getAttribute('color')->getFrontend()->getValue($this->getProduct()) ?>',
			'brand':		'<?php echo $this->getProduct()->getAttributeText('manufacturer') ?>',
			'category': 	'<?php echo Mage::helper('core')->jsQuoteEscape(trim($this->getCategory()->getName())) ?>'
		});

		ecomm.i.push('<?php echo $this->getProduct()->getSku() ?>');
		ecomm.p.push('<?php echo Mage::helper('core')->jsQuoteEscape($this->getProduct()->getName()) ?>');
		ecomm.v.push('<?php echo $this->getProduct()->getFinalPrice() ?>');

		<?php if ($this->getGrouped()) : ?>

			/* Remove grouped product from collection */
			collection.shift();

			/* Remove grouped product from ecomm object */
			ecomm.i.shift()
			ecomm.p.shift();
			ecomm.v.shift();
		
			<?php foreach ($this->getGrouped() as $entity) : ?>

				/* Add associated product to collection */
			
				collection.push(
				{
					'name': 		'<?php echo Mage::helper('core')->jsQuoteEscape($entity->getName()) ?>',
					'id': 		    '<?php echo $entity->getSku() ?>',
					'price': 		'<?php echo $entity->getFinalPrice() ?>',
					'variant':		'<?php echo $entity->getResource()->getAttribute('color')->getFrontend()->getValue($entity) ?>',
					'brand':		'<?php echo $entity->getAttributeText('manufacturer') ?>',
					'category': 	'<?php echo Mage::helper('core')->jsQuoteEscape(trim($this->getCategory()->getName())) ?>'
				});

				/* Add associated product to ecomm object */
				
				ecomm.i.push('<?php echo $entity->getSku() ?>');
				ecomm.p.push('<?php echo Mage::helper('core')->jsQuoteEscape($entity->getName()) ?>');
				ecomm.v.push('<?php echo $entity->getFinalPrice() ?>');
				
			<?php endforeach; ?>
		<?php endif ?>
		
		
		var data = 
		{
			'ecommerce': 
			{
				'detail': 
				{
					'actionField': 
					{
							'list': '<?php echo trim($this->getCategory()->getName()) ?>'
					},
					'products': collection
				}
			}
		};

		if (window.google_tag_params)
		{
			window.google_tag_params.ecomm_pagetype 	= 'product';
			
			window.google_tag_params.ecomm_prodid 		= ecomm.i;
			window.google_tag_params.ecomm_pname 		= ecomm.p;
			window.google_tag_params.ecomm_pvalue 		= ecomm.v;
			window.google_tag_params.ecomm_totalvalue 	= '<?php echo $this->getProduct()->getFinalPrice() ?>';
			window.google_tag_params.ecomm_category		= '<?php echo Mage::helper('core')->jsQuoteEscape(trim($this->getCategory()->getName())) ?>';
			
		}

		dataLayer.push(data);

		if (AEC.debug)
		{
    		console.log('GTM: Product details view track for ' + data.ecommerce.detail.products[0].name);
		}
	});

	/* Create a grouped products collection */
	<?php if ($this->getGrouped()) : ?>
		<?php foreach ($this->getGrouped() as $entity) : ?>
			window.G.push(
			{
				'id'		:'<?php echo $entity->getId() ?>',
				'sku'		:'<?php echo $entity->getSku() ?>',
				'name'		:'<?php echo Mage::helper('core')->jsQuoteEscape($entity->getName()) ?>',
				'price'		:'<?php echo $entity->getFinalPrice() ?>',
				'brand'		:'<?php echo $entity->getAttributeText('manufacturer') ?>',
				'category'	:'<?php echo Mage::helper('core')->jsQuoteEscape(trim($this->getCategory()->getName())) ?>'
			});
		<?php endforeach; ?>
	<?php endif ?>
	
</script>