<script type="text/javascript">
	/** 
	* Magento Enhanced Ecommerce Event Tracking for Google Tag Manager
	*
	* @author Angel Kostadinov
	* @see http://www.anowave.com/marketplace/magento-extensions/magento-google-tag-manager-enhanced-ecommerce-ua-tracking/
	* @copyright Anowave
	* @version 1.0
	*/
	var EC = [], Purchase = [], AEC = {}

	window.dataLayer = window.dataLayer || [];

	/* Dynamic remarketing */
	window.google_tag_params = window.google_tag_params || {};

	/* Default pagetype */
	window.google_tag_params.ecomm_pagetype = 'other';

	/* Set ecomm_pagetype */
	<?php if(Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms') : ?>
	
	window.google_tag_params.ecomm_pagetype = 'home';
	
	<?php endif; ?>

	/* Grouped products collection */
	window.G = [];		
	
	/**
	* EC Purchase
	*
	*/
	<?php if ($this->getOrderIds()) : ?>
		<?php 
			$collection = Mage::getResourceModel('sales/order_collection')->addFieldToFilter('entity_id', array
			(
				'in' => $this->getOrderIds())
			);
			
			foreach ($collection as $order) 
			{
				?>
				var purchaseProducts = [], ecomm = 
				{
						i: [],
						v: [],
						p: []
				};
				
				<?php 
				
				if ($order->getIsVirtual()) 
				{
					$address = $order->getBillingAddress();
				} 
				else 
				{
					$address = $order->getShippingAddress();
				}
				
				/* Sales coupon */
				$coupon = null;
				
				if ($order->getCouponCode())
				{
					$code = Mage::getModel('salesrule/coupon')->load($order->getCouponCode(), 'code');
				
					if ($code)
					{
						$rule = Mage::getModel('salesrule/rule')->load
						(
							$code->getRuleId()
						);
				
						$coupon = $rule->getName();
					}
				}
				
				
				foreach ($order->getAllVisibleItems() as $item) 
				{
					$collection = $item->getProduct()->getCategoryIds();
					
					if (!$collection)
					{
						$collection[] = Mage::app()->getStore()->getRootCategoryId();
					}
					
					$category = Mage::getModel('catalog/category')->load
					(
						end($collection)
					);
					
					?>
				
					purchaseProducts.push(
					{
						'name': 		'<?php echo Mage::helper('core')->jsQuoteEscape($item->getProduct()->getName()) ?>',
				        'id': 		    '<?php echo $item->getProduct()->getSku() ?>',
				        'price': 		'<?php echo $item->getBasePrice() ?>',
				        'quantity': 	'<?php echo $item->getQtyOrdered() ?>',
				        'category':		'<?php echo Mage::helper('core')->jsQuoteEscape($category->getName()) ?>',
				        'brand':		'<?php echo $item->getProduct()->getAttributeText('manufacturer') ?>',
				        'coupon':		'<?php echo $this->jsQuoteEscape($coupon) ?>',
						'variant':		'<?php echo $item->getQuoteItemId() ?>'
					});

					ecomm.i.push('<?php echo $item->getProduct()->getSku() ?>');
					ecomm.v.push('<?php echo $item->getProduct()->getFinalPrice() ?>');
					ecomm.p.push('<?php echo Mage::helper('core')->jsQuoteEscape($item->getProduct()->getName()) ?>');
					
					
					<?php
				}
				
			
				?>

				if (purchaseProducts.length)
				{
					var data = 
					{
						'ecommerce': 
						{
							'purchase': 
							{
								'actionField': 
								{
									'id': 			'<?php echo $order->getIncrementId() ?>',
									'affiliation': 	'<?php echo $this->jsQuoteEscape(Mage::app()->getStore()->getFrontendName()) ?>',
									'revenue': 		'<?php echo $order->getBaseGrandTotal() ?>',
									'tax':			'<?php echo $order->getBaseTaxAmount() ?>',
									'shipping': 	'<?php echo $order->getBaseShippingAmount() ?>',
									'coupon':		'<?php echo $this->jsQuoteEscape($coupon) ?>'
								},
								'products': purchaseProducts
							}
						}
					}

					Purchase.push(data);

					if (window.google_tag_params)
					{
						window.google_tag_params.ecomm_prodid 		= ecomm.i;
						window.google_tag_params.ecomm_pvalue		= ecomm.v;
						window.google_tag_params.ecomm_pname		= ecomm.p;
						window.google_tag_params.ecomm_pagetype 	= 'purchase';
						window.google_tag_params.ecomm_totalvalue 	= '<?php echo $order->getBaseGrandTotal() ?>';
					}

					<?php if ($this->getAdwords()->getGoogleConversionId()) : ?>

					window.google_conversion_value 		= '<?php echo $order->getBaseGrandTotal() ?>';
					
					window.google_conversion_id 		= '<?php echo $this->getAdwords()->getGoogleConversionId() ?>';
					window.google_conversion_language 	= '<?php echo $this->getAdwords()->getGoogleConversionLanguage() ?>';
					window.google_conversion_format 	= '<?php echo $this->getAdwords()->getGoogleConversionFormat() ?>';
					window.google_conversion_label 		= '<?php echo $this->getAdwords()->getGoogleConversionLabel() ?>';
					window.google_conversion_color		= '<?php echo $this->getAdwords()->getGoogleConversionColor() ?>';
					window.google_conversion_currency 	= '<?php echo $this->getAdwords()->getGoogleConversionCurrency() ?>';
					
					<?php endif ?>
	
					if (AEC.debug)
					{
			    		console.log('GTM: Tracked product purchase (Item count: ' + purchaseProducts.length + ')');
					}
				}

				<?php 
			}
		?>
		
		
	<?php endif ?>

	if (Purchase.length)
	{			
		EC.push(function(dataLayer)
		{
			var response = [];
			
			for (i = 0, l = Purchase.length; i < l; i++)
			{
				dataLayer.push(Purchase[i]);
			}
		});
	}			
</script>