<?php
/**
 * @var Goodahead_Authorizenet_Block_Account_Card $this
 */
?>
<div class="padder">
<div class="page-head button-level">
    <h3><?php echo $this->__('Your Stored Payment Info'); ?></h3>
	<a href="<?php echo $this->getNewAction(); ?>">
		<img class="v-middle" alt="<?php echo $this->__('Add New Card'); ?>" src="<?php echo $this->getSkinUrl('images/btn_add_new_card.gif'); ?>"/>
	</a>
	<?php /* ?>
    <button onclick="window.location='<?php echo $this->getNewAction(); ?>'" class="button" title="<?php echo $this->__('Add New Card'); ?>" type="button">
        <span><span><?php echo $this->__('Add New Card'); ?></span></span>
    </button>
	<?php */ ?>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<?php echo $this->getChildHtml('form_before'); ?>
<?php $paymentProfiles = $this->getPaymentProfiles(); ?>
<?php if (!$paymentProfiles): ?>
    <h4><?php echo $this->__('You have no Stored Payment Information yet'); ?></h4>
    <?php return null; ?>
<?php endif; ?>
<div class="col2-set">
    <div class="col-1 primary-address-list">
		<div class="head-alt2">
	        <h4><?php echo $this->__('Credit Card'); ?></h4>
		</div>
        <ol>
            <?php foreach ($paymentProfiles as $id => $paymentProfile): ?>
                <li>
                    <h5><?php echo $paymentProfile['credit_card']['cardNumber']; ?></h5>
                    <address>
                        <?php if (!empty($paymentProfile['billing']['firstName'])): ?>
                            <?php echo $paymentProfile['billing']['firstName'] . ' '; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['lastName'])): ?>
                            <?php echo $paymentProfile['billing']['lastName']; ?>
                        <?php endif; ?><br/>
                        <?php if (!empty($paymentProfile['billing']['company'])): ?>
                            <?php echo $paymentProfile['billing']['company'] . '<br/>'; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['address'])): ?>
                            <?php echo $paymentProfile['billing']['address'] . '<br/>'; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['city'])): ?>
                            <?php echo $paymentProfile['billing']['city'] . ','; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['state'])): ?>
                            <?php echo $paymentProfile['billing']['state'] . ','; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['zip'])): ?>
                            <?php echo $paymentProfile['billing']['zip']; ?>
                        <?php endif; ?><br/>
                        <?php if (!empty($paymentProfile['billing']['country'])): ?>
                            <?php echo $paymentProfile['billing']['country'] . '<br/>'; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['phoneNumber'])): ?>
                            <?php echo 'T: ' . $paymentProfile['billing']['phoneNumber']; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['faxNumber'])): ?>
                            <?php echo '<br/>F: ' . $paymentProfile['billing']['faxNumber']; ?>
                        <?php endif; ?>
                    </address>
                    <p class="profile-links">
                        <a class="link-edit" href="<?php echo $this->getEditAction().'id/'.$id; ?>"><?php echo $this->__('Edit Card'); ?></a>
                        <a class="link-remove" href="#" onclick="deleteCard('<?php echo $id; ?>');"><?php echo $this->__('Delete Card'); ?></a>
                    </p>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
</div>
</div>
<script type="text/javascript">
    function deleteCard(cardId) {
        if (confirm('<?php echo $this->__('Are you sure you want to delete this card?'); ?>')) {
            window.location = '<?php echo $this->getDeleteAction() . 'id/'; ?>' + cardId;
        }
        return false;
    }
</script>
