<div id="block_notice_wizard_congratulation" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__(''); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php

    $listingTemplatesUrl = $this->getUrl('*/adminhtml_template_general/index');
    $synchronizationTemplatesUrl = $this->getUrl('*/adminhtml_template_synchronization/index');
    $descriptionTemplatesUrl = $this->getUrl('*/adminhtml_template_description/index');
    $sellingFormatTemplatesUrl = $this->getUrl('*/adminhtml_template_sellingFormat/index');

    $listingsUrl = $this->getUrl('*/adminhtml_listing/index');
    $docsLink = Mage::helper('M2ePro/Module')->getConfig()->getGroupValue('/documentation/', 'baseurl');

    $menuLabel = Mage::helper('M2ePro/Module')->getMenuRootNodeLabel();

    $components = array();

    if (Mage::helper('M2ePro/Component_Ebay')->isAllowed()) {
        $components[Ess_M2ePro_Helper_Component_Ebay::NICK] = Ess_M2ePro_Helper_Component_Ebay::TITLE;
    }
    if (Mage::helper('M2ePro/Component_Amazon')->isAllowed()) {
        $components[Ess_M2ePro_Helper_Component_Amazon::NICK] = Ess_M2ePro_Helper_Component_Amazon::TITLE;
    }

    $components = implode(' / ',$components);

    $tempString = Mage::helper('M2ePro')->__(
        'You have set the main M2E Pro settings and now you have to set up the main settings of the chosen Channel(s).'
    );

    echo str_replace(
        array('%sel%',
            '%descr%',
            '%list_temp%',
            '%synch%',
            '%list%',
            '%menu_label%',
            '%docs_link%',
            '%components%'),
        array(
            $sellingFormatTemplatesUrl,
            $descriptionTemplatesUrl,
            $listingTemplatesUrl,
            $synchronizationTemplatesUrl,
            $listingsUrl,
            $menuLabel,
            $docsLink,
            $components
        ),
        $tempString
    );

    ?>
</div>