<div id="block_notice_wizard_welcome_description" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__(''); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php $tempString = Mage::helper('M2ePro')->__('<strong>You have successfully installed M2E Pro v. %ver%.</strong><br/><br/>
    The next step is setting up of the main settings, such as Cron job, Licensing (extension does not work without license)
    and others to enable a proper work of the extension.<br/>
    In the table below there are recommended server settings, which guaranty stable working of the extension. <br/><br/>
    Press the <span style="text-decoration: underline;">Start Configuration</span> button to start setting M2E Pro configuration.');
    echo str_replace('%ver%',$this->version,$tempString); ?>
</div>