<div class="intermix">
    <a href="<?php echo 'http://www.intermixbev.com'?>"><img src="<?php echo $this->getSkinUrl('images/intermix.png') ?>" alt="" /></a>
</div>
<div class="whosalestore">
    <a href="<?php echo $this->getWebsiteUrl('base')?>"><img src="<?php echo $this->getSkinUrl('images/whosalestore.png') ?>" alt="" /></a>
</div>
<div class="volumestore">
    <a href="<?php echo $this->getWebsiteUrl('volume')?>"><img src="<?php echo $this->getSkinUrl('images/volumestore.png') ?>" alt="" /></a>
</div>
