<div id="block_notice_wizard_welcome_content" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__(''); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php
    $tempString = Mage::helper('M2ePro')->__(
        'This part of extension allows quick and simple creation as well as management of product listings on eBay
        (inc. automated synchronization of stock levels, pricing, and product details), import of eBay Transactions, automated
        feedback posting for buyers and many other tasks which significantly reduce time required for listing maintenance.'
    );
    echo str_replace('%ver%',Mage::helper('M2ePro/Module')->getVersion(),$tempString); ?>
</div>