<div id="block_notice_amazon_template_description" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Description'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
    'Description is used to design your items\' description on Amazon.<br/><br/>
    It is possible to choose a Product Description or Product Short Description, which will be taken from Magento. Or you can create a Custom Description by adding necessary information.'
); ?>
</div>

<?php

$formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data') : array();
isset($formData['description']) ? $formData = $formData['description'] : $formData = array();

!empty($formData['bullet_points']) && $formData['bullet_points'] = json_decode($formData['bullet_points'], true);

$default = array(
    'title' => '',

    'title_mode' => Ess_M2ePro_Model_Amazon_Category_Description::TITLE_MODE_PRODUCT,
    'title_template' => '',

    'brand_mode' => Ess_M2ePro_Model_Amazon_Category_Description::BRAND_MODE_NONE,
    'brand_template' => '',

    'manufacturer_mode' => Ess_M2ePro_Model_Amazon_Category_Description::MANUFACTURER_MODE_NONE,
    'manufacturer_template' => '',

    'manufacturer_part_number_mode' => Ess_M2ePro_Model_Amazon_Category_Description::MANUFACTURER_PART_NUMBER_MODE_NONE,
    'manufacturer_part_number_template' => '',

    'image_main_mode' => Ess_M2ePro_Model_Amazon_Category_Description::IMAGE_MAIN_MODE_PRODUCT,
    'image_main_attribute' => '',
    'gallery_images_mode' => 0,

    'bullet_points_mode' => Ess_M2ePro_Model_Amazon_Category_Description::BULLET_POINTS_MODE_NONE,
    'bullet_points' => array(),

    'description_mode' => Ess_M2ePro_Model_Amazon_Category_Description::DESCRIPTION_MODE_NONE,
    'description_template' => '',
);

$formData = array_merge($default, $formData);

$isEdit = !!$this->getRequest()->getParam('id');

?>

<script type="text/javascript">

    Event.observe(window, 'load', function() {
        AmazonTemplateDescriptionHandlerObj = new AmazonTemplateDescriptionHandler();
        AmazonTemplateDescriptionHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Template_Description'); ?>');
        AmazonTemplateDescriptionHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Amazon_Category_Description'); ?>');

        M2ePro.formData.image_main_attribute = '<?php echo $formData['image_main_attribute']; ?>';

        $('amazonCategoryEditTabs_description').observe('click', AmazonCategoryHandlerObj.checkAttributeSetSelection);

        $('attribute_sets_confirm_button').observe('click',AmazonTemplateDescriptionHandlerObj.attribute_sets_confirm.bind(AmazonTemplateDescriptionHandlerObj));

        $('attribute_sets').value && AmazonTemplateDescriptionHandlerObj.attribute_sets_confirm();

        $('title_mode')
            .observe('change', AmazonTemplateDescriptionHandlerObj.title_mode_change)
            .simulate('change');

        $('brand_mode')
            .observe('change', AmazonTemplateDescriptionHandlerObj.brand_mode_change)
            .simulate('change');

        $('manufacturer_mode')
            .observe('change', AmazonTemplateDescriptionHandlerObj.manufacturer_mode_change)
            .simulate('change');

        $('manufacturer_part_number_mode')
            .observe('change', AmazonTemplateDescriptionHandlerObj.manufacturer_part_number_mode_change)
            .simulate('change');

        $('bullet_points_mode')
            .observe('change', AmazonTemplateDescriptionHandlerObj.bullet_points_mode_change)
            .simulate('change');

        $('description_mode')
            .observe('change', AmazonTemplateDescriptionHandlerObj.description_mode_change)
            .simulate('change');

        $('image_main_mode')
            .observe('change', AmazonTemplateDescriptionHandlerObj.image_main_mode_change)
            .simulate('change');
    });

</script>

<style type="text/css">

    .input-text-small {
        width: 120px !important;
    }
    .textarea {
        width: 98% !important;
        height: 500px !important;
    }
    select.select-main {
        width: 356px !important;
    }
    .select-wrapper {
        margin-left: 15px;
    }
    a.action-disabled {
        color: gray !important;
        text-decoration: none !important;
    }
    a.action-disabled:hover {
        color: gray !important;
        text-decoration: none !important;
    }
    td.value {
        width: auto !important;
    }
</style>

<div class="entry-edit" id="magento_block_amazon_template_description_details">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Item Details'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Item Title'); ?>: </label>
                    </td>
                    <td class="value">
                        <select id="title_mode" name="description[title_mode]" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::TITLE_MODE_PRODUCT; ?>" <?php if ($formData['title_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::TITLE_MODE_PRODUCT): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Name'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::TITLE_MODE_CUSTOM; ?>" <?php if ($formData['title_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::TITLE_MODE_CUSTOM): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Title'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Item\'s title that buyers will see on Amazon listing.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="custom_title_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Custom Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="title_template" name="description[title_template]" value="<?php echo Mage::helper('M2ePro')->__($formData['title_template']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                        <span id="select_attributes_for_title_span" class="select-wrapper"></span>
                        <?php echo $this->getChildHtml('select_attributes_for_title_button'); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Item Brand'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="brand_mode" name="description[brand_mode]" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::BRAND_MODE_NONE; ?>" <?php if ($formData['brand_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::BRAND_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::BRAND_MODE_CUSTOM; ?>" <?php if ($formData['brand_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::BRAND_MODE_CUSTOM): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Brand'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Brand of the product(s). Max. 50 characters.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="custom_brand_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Custom Brand'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="brand_template" name="description[brand_template]" value="<?php echo Mage::helper('M2ePro')->__($formData['brand_template']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                        <span id="select_attributes_for_brand_span" class="select-wrapper"></span>
                        <?php echo $this->getChildHtml('select_attributes_for_brand_button'); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Item Manufacturer'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="manufacturer_mode" name="description[manufacturer_mode]" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::MANUFACTURER_MODE_NONE; ?>" <?php if ($formData['manufacturer_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::MANUFACTURER_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::MANUFACTURER_MODE_CUSTOM; ?>" <?php if ($formData['manufacturer_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::MANUFACTURER_MODE_CUSTOM): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Manufacturer'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Manufacturer of the product(s). Max. 50 characters.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="custom_manufacturer_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Custom Manufacturer'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="manufacturer_template" name="description[manufacturer_template]" value="<?php echo Mage::helper('M2ePro')->__($formData['manufacturer_template']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                        <span id="select_attributes_for_manufacturer_span" class="select-wrapper"></span>
                        <?php echo $this->getChildHtml('select_attributes_for_manufacturer_button'); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Item Manufacturer Part Number'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="manufacturer_part_number_mode" name="description[manufacturer_part_number_mode]" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::MANUFACTURER_PART_NUMBER_MODE_NONE; ?>" <?php if ($formData['manufacturer_part_number_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::MANUFACTURER_PART_NUMBER_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::MANUFACTURER_PART_NUMBER_MODE_CUSTOM; ?>" <?php if ($formData['manufacturer_part_number_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::MANUFACTURER_PART_NUMBER_MODE_CUSTOM): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Manufacturer Part Number'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Manufacturer of the product(s). Max. 50 characters.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="custom_manufacturer_part_number_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Custom Manufacturer Part Number'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="manufacturer_part_number_template" name="description[manufacturer_part_number_template]" value="<?php echo Mage::helper('M2ePro')->__($formData['manufacturer_part_number_template']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                        <span id="select_attributes_for_manufacturer_part_number_span" class="select-wrapper"></span>
                        <?php echo $this->getChildHtml('select_attributes_for_manufacturer_part_number_button'); ?>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_template_description_image">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Images'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr class="requirie-attribute-set">
                    <td class="label">
                        <label for="image_main_mode"><?php echo Mage::helper('M2ePro')->__('Main Item Image'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="image_main_mode" name="description[image_main_mode]">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::IMAGE_MAIN_MODE_NONE; ?>" <?php if ($formData['image_main_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::IMAGE_MAIN_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::IMAGE_MAIN_MODE_PRODUCT; ?>" <?php if ($formData['image_main_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::IMAGE_MAIN_MODE_PRODUCT): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Base Image'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::IMAGE_MAIN_MODE_ATTRIBUTE; ?>" <?php if ($formData['image_main_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::IMAGE_MAIN_MODE_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Image you will see on your Amazon listing.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="image_main_attribute_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Product Image Attribute'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <div id="image_main_attribute_td"></div>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Choose Media Image Attribute or Attribute, that contains absolute url.
                            <br/>i.e. http://mymagentostore.com/images/baseimage.jpg'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="gallery_images_mode_tr">
                    <td class="label">
                        <label for="gallery_images_mode"><?php echo Mage::helper('M2ePro')->__('Item Gallery Images'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="gallery_images_mode" name="description[gallery_images_mode]">
                            <option value="0" <?php if ($formData['gallery_images_mode'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="1" <?php if ($formData['gallery_images_mode'] == 1): echo ' selected="selected"'; endif; ?>>1</option>
                            <?php for ($i = 2; $i <= 8; $i++): ?>
                                <option value="<?php echo $i; ?>" <?php if ($formData['gallery_images_mode'] == $i): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Up to').' '.$i; ?></option>
                            <?php endfor ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('The number of images in item\'s gallery.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_template_description_bullet_points">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Bullet Points'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0" style="width:100%">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Bullet Points Mode') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="bullet_points_mode" name="description[bullet_points_mode]" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::BULLET_POINTS_MODE_NONE; ?>" <?php if ($formData['bullet_points_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::BULLET_POINTS_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::BULLET_POINTS_MODE_CUSTOM; ?>" <?php if ($formData['bullet_points_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::BULLET_POINTS_MODE_CUSTOM): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Bullet Points'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Allows highlighting some of the product\'s most important qualities.'); ?></span>
                        </p>
                    </td>
                </tr>

                <?php for ($i = 0; $i < 5; $i++): ?>
                    <tr class="bullet-points-tr" style="display: none;">
                        <td class="label">
                            <label><?php $label = Mage::helper('M2ePro')->__('Value #%num%'); echo str_replace('%num%', $i + 1, $label); ?>:</label>
                        </td>
                        <td class="value">
                            <input id="bullet_points_<?php echo $i; ?>" name="description[bullet_points][]" type="text" class="input-text M2ePro-required-when-visible" value="<?php echo !empty($formData['bullet_points'][$i]) ? $formData['bullet_points'][$i] : ''; ?>">
                            <span id="select_attributes_for_bullet_points_<?php echo $i; ?>_span" class="select-wrapper"></span>
                            <?php echo $this->getChildHtml("select_attributes_for_bullet_points_{$i}_button"); ?>
            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Max. 100 characters.'); ?></span>
                            </p>
                        </td>
                    </tr>
                <?php endfor; ?>

                <tr id="bullet_point_actions_tr" style="display: none;">
                    <td></td>
                    <td class="value" style="padding-top: 0 !important;">
                        <a id="show_bullet_point_action" href="javascript: void(0);" onclick="AmazonTemplateDescriptionHandlerObj.showBulletPoint();"><?php echo Mage::helper('M2ePro')->__('Add New') ?></a>
                        /
                        <a id="hide_bullet_point_action" href="javascript: void(0);" onclick="AmazonTemplateDescriptionHandlerObj.hideBulletPoint();"><?php echo Mage::helper('M2ePro')->__('Remove') ?></a>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_template_description_description">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Description'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0" style="width:100%">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Description Source'); ?>: </label>
                        </td>
                        <td class="value">
                            <select id="description_mode" name="description[description_mode]" class="required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::DESCRIPTION_MODE_NONE; ?>" <?php if ($formData['description_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::DESCRIPTION_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::DESCRIPTION_MODE_PRODUCT; ?>" <?php if ($formData['description_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::DESCRIPTION_MODE_PRODUCT): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Description'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::DESCRIPTION_MODE_SHORT; ?>" <?php if ($formData['description_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::DESCRIPTION_MODE_SHORT): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Short Description'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Category_Description::DESCRIPTION_MODE_CUSTOM; ?>" <?php if ($formData['description_mode'] == Ess_M2ePro_Model_Amazon_Category_Description::DESCRIPTION_MODE_CUSTOM): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Description'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Item description is limited to 2\'000 characters or less.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr class="c-custom_description_tr" style="display: none;">
                        <td class="label"></td>
                        <td class="value">

                            <script type="text/javascript">
                                wysiwygtext = {
                                    isEnabled: function() {
                                        return false;
                                    }
                                };
                            </script>

                            <textarea id="description_template" name="description[description_template]" class="textarea"><?php echo Mage::helper('M2ePro')->escapeHtml($formData['description_template']); ?></textarea>

                        </td>
                    </tr>

                    <tr class="c-custom_description_tr" style="display: none;">
                        <td class="label"></td>
                        <td class="value">

                            <div class="entry-edit-head" style="background: #D6D6D6;">
                                <h4 class="icon-head head-edit-form fieldset-legend" style="color: #EA7601;"><?php echo Mage::helper('M2ePro')->__('Custom Description Inserts'); ?></h4>
                            </div>

                            <div class="fieldset">
                                <div class="hor-scroll">
                                    <table cellspacing="0" class="form-list">
                                        <tr>
                                            <td class="label">
                                                <label for="select_attributes_span"><?php echo Mage::helper('M2ePro')->__('Product Attribute');?>:</label>
                                            </td>
                                            <td class="value">
                                                <span id="select_attributes_span"></span>
                                                &nbsp;
                                                <?php echo $this->getChildHtml('add_product_attribute_button'); ?>
                                                <p class="note">
                                                    <span><?php echo Mage::helper('M2ePro')->__('Attributes related to the previously chosen Attribute Set.'); ?></span>
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>

                        </td>
                    </tr>

                </table>

            </div>
        </div>
    </div>