<div id="block_notice_category_add" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General tab TODO TEXT'); ?>">
    <?php echo Mage::helper('M2ePro')->__('TODO TEXT'); ?>
</div>

<?php
$formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data') : array();
$default = array(
    'category' => array(
        'id' => '',
        'attribute_sets' => array(),
        'path' => '',
        'xsd_hash' => '',
        'node_title' => '',
        'identifiers' => json_encode(array('item_types' => null, 'browsenode_id' => null))
    ),
    'specifics' => array()
);

$formData = array_merge($default, $formData);

$formData['category']['identifiers'] = Mage::helper('M2ePro')->escapeHtml($formData['category']['identifiers']);

$isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.text.internal_error = '<?php echo Mage::helper('M2ePro')->__('Internal Error. Please try again later.'); ?>';

    M2ePro.text.browse_category = '<?php echo Mage::helper('M2ePro')->__('Browse For Category'); ?>';
    M2ePro.text.search_category = '<?php echo Mage::helper('M2ePro')->__('Search For Category'); ?>';

    M2ePro.text.select_category_first = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should select Category first')); ?>';
    M2ePro.text.attribute_set_not_selected_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should select Attribute Set first')); ?>';
    M2ePro.text.press_choose_btn = '<?php echo Mage::helper('M2ePro')->__('This is a required field. Please press Choose button.'); ?>';
    M2ePro.text.invalid_data = '<?php echo Mage::helper('M2ePro')->__('Incorrect data.'); ?>';
    M2ePro.text.title_not_unique_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The specified title is already used for other category.')); ?>';
    M2ePro.text.allower_values = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Allowed Values: ')); ?>';

    M2ePro.formData  = <?php echo json_encode($formData); ?>;

    M2ePro.url.magentoGetAttributesByAttributeSets = '<?php echo $this->getUrl('*/adminhtml_general/magentoGetAttributesByAttributeSets'); ?>';

    M2ePro.url.searchCategory = '<?php echo $this->getUrl('*/adminhtml_amazon_category/searchCategory',array('marketplace_id'=>$this->marketplaceId)); ?>';

    M2ePro.url.getXsds = '<?php echo $this->getUrl('*/adminhtml_amazon_category/getXsds',array('marketplace_id'=>$this->marketplaceId)); ?>';
    M2ePro.url.getSpecifics = '<?php echo $this->getUrl('*/adminhtml_amazon_category/getSpecifics'); ?>';
    M2ePro.url.getCategories = '<?php echo $this->getUrl('*/adminhtml_amazon_category/getCategories',array('marketplace_id'=>$this->marketplaceId)); ?>';
    M2ePro.url.check_repetition = '<?php echo $this->getUrl('*/adminhtml_amazon_category/checkRepetition',array('marketplace_id'=>$this->marketplaceId)); ?>';

    M2ePro.url.helpIcon = '<?php echo $this->getSkinUrl('images').'/fam_help.gif'; ?>';

    Event.observe(window, 'load', function() {

        AttributeSetHandlerObj = new AttributeSetHandler();
        AmazonCategoryHandlerObj = new AmazonCategoryHandler(M2ePro,new AmazonCategorySpecificHandler(M2ePro));

        $('attribute_sets_confirm_button').observe('click',AmazonCategoryHandlerObj.confirmAttributeSets.bind(AmazonCategoryHandlerObj));

        $('attribute_sets').observe('change', AttributeSetHandlerObj.changeAttributeSets);
        $('attribute_sets').value && AttributeSetHandlerObj.confirmAttributeSets();

        $('node_title').observe('change', function(event) {
            AmazonCategoryHandlerObj.node_title_change(this);
        });

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });

    //-----------------------------

</script>

<input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />
<input name="category[id]" value="<?php echo $formData['category']['id']; ?>" type="hidden" />

<div class="entry-edit" id="magento_block_category_edit_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Category Configuration'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="attribute_sets"><?php echo Mage::helper('M2ePro')->__('Attribute Sets'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <div id="attribute_sets_container" <?php if ($this->attribute_set_locked): ?>style="display: none;"<?php endif; ?>>
                                <?php $this->attribute_set_locked ? $attributeSetPostfix = '_fake' : $attributeSetPostfix = ''; ?>
                                <select id="attribute_sets<?php echo $attributeSetPostfix; ?>" name="category[attribute_sets<?php echo $attributeSetPostfix; ?>][]" multiple="multiple" class="<?php if (!$this->attribute_set_locked): ?>M2ePro-validate-attribute-sets<?php endif; ?>">
                                    <?php foreach ($this->getData('attributes_sets') as $set): ?>
                                        <option value="<?php echo $set['attribute_set_id']; ?>"<?php if (in_array($set['attribute_set_id'], $formData['category']['attribute_sets'])): echo ' selected="selected"'; endif;?>><?php echo $set['attribute_set_name'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <?php if ($this->attribute_set_locked): ?>
                                <div id="attribute_sets_breadcrumb" style="width: 280px;">
                                    <?php $breadcrumb = array(); foreach ($this->getData('attributes_sets') as $set): ?>
                                        <?php if (in_array($set['attribute_set_id'], $formData['category']['attribute_sets'])): $breadcrumb[] = $set['attribute_set_name']; endif; ?>
                                    <?php endforeach; ?>
                                    <strong><?php echo implode(', ', $breadcrumb); ?></strong>
                                </div>
                                <input id="attribute_sets" name="category[attribute_sets]" value="<?php echo $this->escapeHtml(implode(',', $formData['category']['attribute_sets'])); ?>" type="hidden" />
                            <?php endif; ?>

                            <div id="attribute_sets_buttons_container" style="padding-top: 5px; <?php if ($this->attribute_set_locked): ?>display: none;<?php endif; ?>">
                                <?php echo $this->getChildHtml('attribute_sets_select_all_button'); ?>
                                <?php echo $this->getChildHtml('attribute_sets_confirm_button'); ?>
                            </div>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('TODO TEXT'); ?></span>
                            </p>
                        </td>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Category'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <div <?php if ($isEdit) echo 'style="display: none"'?>>
                            <span style="margin: 0 10px 0 0">
                                <?php echo $this->getChildHtml('browse_category_button'); ?>
                            </span>
                            <strong><?php echo Mage::helper('M2ePro')->__('or'); ?></strong>
                            <span style="margin: 0 0 0 10px">
                                <?php echo $this->getChildHtml('search_category_button'); ?>
                            </span>
                        </div>
                        <div>
                            <p id="category_change_button_container" style="display: none; margin: 1px 0 0 0">
                                <?php echo $this->getChildHtml('category_change_button'); ?>
                            </p>
                        </div>
                    </td>
                </tr>

            </table>

            <div>
                <?php if ($formData['category']['node_title']) { ?>
                    <?php foreach ($this->nodes as $node) {
                        if ($node['title'] == $formData['category']['node_title']) {
                            echo '<input id="node_hash" name="node_hash" value="'.$node['hash'].'" type="hidden" />';
                            break;
                        }
                    } ?>
                    <input type="hidden" name="category[node_title]" value="<?php echo $formData['category']['node_title']; ?>"/>
                <?php } else { ?>
                    <input type="hidden" name="category[node_title]" value=""/>
                <?php } ?>

                <input type="hidden" name="category[xsd_hash]" id="xsd_hash" value="<?php echo $formData['category']['xsd_hash']; ?>" />
                <input type="hidden" name="category[identifiers]" id="category_identifiers" value="<?php echo $formData['category']['identifiers']; ?>" />

            </div>

        </div>
    </div>

</div>

<div style="display: none">

    <div class="entry-edit" id="browse_category" style="margin-top: 15px;">

        <div style="height: 450px">
            <div id="block_notice_browse_category" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('TODO TEXT.Browse for category, department'); ?>">
                <?php echo Mage::helper('M2ePro')->__('TODO TEXT'); ?>
            </div>

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Category Configuration'); ?></h4>
            </div>

            <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellpadding="0" cellspacing="0">

                 <tr>
                    <td class="label">
                        <label for="node_title"><?php echo Mage::helper('M2ePro')->__('Department'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">

                        <select id="node_title" name="category[node_title]" class="required-entry">
                            <option style="display: none"></option>
                            <?php foreach ($this->nodes as $node) { ?>
                                <option value="<?php echo $node['title'] ;?>" node_hash="<?php echo $node['hash']; ?>"> <?php echo $node['title'] ;?></option>
                            <?php } ?>
                        </select>

                    </td>
                </tr>

                <tr id="categories_tr" <?php if (empty($formData['category']['category_path'])) : ?> style="display: none;" <?php endif; ?>>

                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Category'); ?>: <span class="required">*</span></label>
                    </td>

                    <td class="value" style="width: 300px">

                        <table>
                            <tr>
                                <td>
                                    <div id="categories_container"></div>
                                </td>
                            </tr>
                        </table>

                        <p id="category_confirm_button_container" style="display: none; margin: 1px 0 0 0; float: left">
                            <?php echo $this->getChildHtml('category_confirm_button'); ?>
                        </p>

                    </td>

                </tr>

                <tr id="xsds_tr" style="display: none;">

                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Subcategory'); ?>: <span class="required">*</span></label>
                    </td>

                    <td class="value" style="width: auto;">

                        <div id="xsd_hash_container">

                        </div>

                    </td>

                </tr>
            </table>

            </div>
        </div>
        </div>

        <div class="right" style="margin-right: 15px">
            <?php echo $this->getChildHtml('close_browse_popup_button'); ?>
        </div>

    </div>

    <div class="entry-edit" id="search_category" style="margin-top: 15px">

        <div id="error_block" class="error-msg" style="margin-bottom: 10px; display: none">
            <div style="margin: 10px 0px 10px 35px">
                <div id="error_message" style="font-weight:bold"></div>
            </div>
        </div>

        <div id="block_notice_search_category" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('TODO TEXT.Search for category'); ?>">
            <?php echo Mage::helper('M2ePro')->__('TODO TEXT'); ?>
        </div>

        <div style="padding: 10px; border: 1px solid rgb(205, 221, 221) !important; background-image: none !important; background-attachment: scroll !important; background-color: rgb(231, 239, 239) !important; background-position: 0px 0px !important; background-repeat: repeat repeat !important;">

            <label for="search_keywords" style="margin-right: 10px"><?php echo Mage::helper('M2ePro')->__('Enter Keywords'); ?></label>
            <input id="search_keywords" style="margin-right: 5px;padding: 4px; color: gray;" name="search_keywords" value="Example: mp3 player, baseball glove, DVD, guitar, etc" class="input-text" type="text" size="60"
                   onblur="if (this.value.trim().length == 0) {
                       this.value = 'Example: mp3 player, baseball glove, DVD, guitar, etc';
                       this.style.color = 'gray';
                   }"
                   onfocus="if (this.value == 'Example: mp3 player, baseball glove, DVD, guitar, etc') {
                       this.value = '';
                       this.style.color = '';
                   }"
                   onkeypress="if (event.keyCode == 13) {
                       AmazonCategoryHandlerObj.searchClick();
                   }"
            >

            <?php echo $this->getChildHtml('search_category_popup_button'); ?>
            &nbsp;
            <?php echo $this->getChildHtml('reset_category_popup_button'); ?>

        </div>

        <div id="searchGrid" style="margin: 10px auto; height: 350px !important; overflow-y: auto; overflow-x: hidden;">
        </div>

        <div class="right" style="margin-right: 15px">
            <?php echo $this->getChildHtml('close_search_popup_button'); ?>
        </div>

    </div>

</div>