<div id="block_notice_wizard_installation_step_amazon_accounts" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Amazon Accounts Set Up'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes" style="display:none;">
    <div>
        <div class="step_container_description">
            <?php echo Mage::helper('M2ePro')->__('Adding your Amazon accounts to M2E Pro extension.'); ?>
        </div>
        <div class="step_container_completed">
            <span class="step_completed" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Completed'); ?></span>
        </div>
        <div class="step_container_incomplete">
            <span class="step_incomplete" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Incomplete'); ?></span>
        </div>
        <div style="clear:both;"></div>
    </div>
    <div class="step_container_buttons">
        <span class="step_skip" style="display:none;"><?php echo $this->getChildHtml('skip_amazon_accounts_button'); ?></span>
        <span class="step_process" style="display:none;"><?php echo $this->getChildHtml('process_amazon_accounts_button'); ?></span>
    </div>
</div>

<script type="text/javascript">
    WizardHandlerObj.addStep(<?php echo Ess_M2ePro_Model_Wizard::STATUS_ACCOUNTS_AMAZON; ?>, 'block_notice_wizard_installation_step_amazon_accounts');
</script>