<?php if (!Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>

    <div id="block_notice_wizard_installation_step_cron" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Cron Job Set Up'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes" style="display:none;">
        <div>
            <div class="step_container_description">
                <?php echo Mage::helper('M2ePro')->__('Set up a cron job to run every 5 minutes to enable automatic working of the extension.<br/>
                Otherwise, some processes will not work (i.e. synchronization tasks, logs cleaning).'); ?>
                <div style="padding-top:5px;">
                    <strong><?php echo Mage::helper('M2ePro')->__('Set up Cron Job using PHP'); ?>:</strong> <br/>
                    <input type="text" style="width:400px;" readonly="readonly" value="php -q <?php echo $this->basePath . DIRECTORY_SEPARATOR; ?>cron.php" onclick="this.select();" />
                </div>
                <div style="padding-top:5px; color: brown;">
                    <strong><?php echo Mage::helper('M2ePro')->__('OR'); ?></strong>
                </div>
                <div style="padding-top:5px;">
                    <strong><?php echo Mage::helper('M2ePro')->__('Set up Cron Job using GET'); ?>:</strong> <br/>
                    <input type="text" style="width:400px;" readonly="readonly" value="<?php echo $this->baseUrl; ?>cron.php" onclick="this.select();" />
                </div>
            </div>
            <div class="step_container_completed">
                <span class="step_completed" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Completed'); ?></span>
            </div>
            <div class="step_container_incomplete">
                <span class="step_incomplete" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Incomplete'); ?></span>
            </div>
            <div style="clear:both;"></div>
        </div>
        <div class="step_container_buttons">
            <span class="step_skip" style="display:none;"><?php echo $this->getChildHtml('skip_cron_button'); ?></span>
            <span class="step_process" style="display:none;"></span>
        </div>
    </div>

<?php } else { ?>

    <div id="block_notice_wizard_installation_step_cron" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Cron Job Set Up'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes" style="display:none;">
        <div>
            <div class="step_container_description">
                <?php echo Mage::helper('M2ePro')->__('Cron is already set up on Magento Go.'); ?>
            </div>
            <div class="step_container_completed">
                <span class="step_completed" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Completed'); ?></span>
            </div>
            <div style="clear:both;"></div>
        </div>
    </div>

<?php } ?>

<script type="text/javascript">
    WizardHandlerObj.addStep(<?php echo Ess_M2ePro_Model_Wizard::STATUS_CRON; ?>, 'block_notice_wizard_installation_step_cron');

    <?php if (Mage::helper('M2ePro/Magento')->isGoEdition() && Mage::getSingleton('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_CRON) { ?>
        setTimeout(function() {
            // we need to wait until next steps will be added to skip current step
            WizardHandlerObj.skipStep(<?php echo Ess_M2ePro_Model_Wizard::STATUS_CRON ?>);
        }, 250);
    <?php } ?>
</script>