<?php

$version = Mage::helper('M2ePro/Module')->getVersion();
$skipWizardLink = $this->getUrl("*/adminhtml_wizard_amazon/skip");
$startWizardLink = $this->getUrl("*/adminhtml_wizard_amazon");

?>

<script type="text/javascript" src="<?php echo $this->getJsUrl('M2ePro/VideoTutorialHandler.js'); ?>"></script>

<script type="text/javascript">

    if (typeof M2eProAmazonUpgradeTutorial == 'undefined') {
        M2eProAmazonUpgradeTutorial = {};
        M2eProAmazonUpgradeTutorial.url = {};
        M2eProAmazonUpgradeTutorial.formData = {};
        M2eProAmazonUpgradeTutorial.text = {};
    }

    M2eProAmazonUpgradeTutorial.text.confim_offer_show_video = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('It is strongly recommended to watch 5 min. video tutorial before starting configuration. Would you like to watch the video?')); ?>';
    M2eProAmazonUpgradeTutorial.text.confim_close_video = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Are you sure?')); ?>';

    AmazonUpgradeVideoTutorialHandlerObj = new VideoTutorialHandler(
        M2eProAmazonUpgradeTutorial,'amazon_upgrade_video_tutorial_pop_up',
        '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('M2E Pro - Amazon/Magento Integration : Configuration Wizard')); ?>',
        function(){setLocation('<?php echo $startWizardLink; ?>');}
    );

</script>

<div class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Amazon Channel'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <div>
       Setting up settings to be able to sell on <strong>Amazon</strong>.
    </div>

    <div class="step_container_buttons">
        <?php echo $this->getChildHtml('continue_button'); ?>
    </div>
</div>

<div id="amazon_upgrade_video_tutorial_pop_up" style="display: none;">
    <div class="player_container" style="margin: 20px 5px; ">
        <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/VDeoadfO2gA?version=3&amp;hl=ru_RU&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/VDeoadfO2gA?version=3&amp;hl=ru_RU&amp;rel=0" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
    </div>
</div>