<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Onestepcheckout
 * @version    1.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if($this->getItemCount()): ?>
<div id="aw-onestepcheckout-related-block">
    <h2><?php echo $this->__('Related Products:') ?></h2>
    <ul id="aw-onestepcheckout-related-block-products-list">
        <?php foreach ($this->getItems() as $_item): ?>
        <li class="aw-onestepcheckout-related-block-item">
            <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(150); ?>" width="150" height="150" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
            <div class="product-details">
                <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_item, true) ?>
                <a href="#" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><img src="<?php echo $this->getSkinUrl('images/btn_add_to_cart.gif') ?>" alt="<?php echo $this->__('Add to Cart') ?>" title="<?php echo $this->__('Add to Cart') ?>" /></a>
                <ul class="add-to">
                    <?php if ($this->isNotAddedToWishlist($_item)): ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                    <?php else:?>
                        <li><?php echo $this->__('Added to Wishlist') ?></li>
                    <?php endif;?>
                    <?php if ($this->isNotAddedToCompareList($_item)): ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                        <li><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif;?>
                    <?php else:?>
                        <li><?php echo $this->__('Added to Compare') ?></li>
                    <?php endif;?>
                </ul>                
            </div>
        </li>
        <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('aw-onestepcheckout-related-crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>