<?php
/**
 * @var Goodahead_Authorizenet_Block_Account_Card $this
 */
?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Your Stored Payment Info'); ?></h1>
    <button onclick="window.location='<?php echo $this->getNewAction(); ?>'" class="button" title="<?php echo $this->__('Add New Card'); ?>" type="button">
        <span><span><?php echo $this->__('Add New Card'); ?></span></span>
    </button>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before'); ?>
<?php $paymentProfiles = $this->getPaymentProfiles(); ?>
<?php if (!$paymentProfiles): ?>
    <h2><?php echo $this->__('You have no Stored Payment Information yet'); ?></h2>
    <?php return null; ?>
<?php endif; ?>
<div class="col2-set addresses-list">
    <div class="col-1">
        <h2><?php echo $this->__('Payment Profiles'); ?></h2>
        <ol>
            <?php foreach ($paymentProfiles as $id => $paymentProfile): ?>
                <li class="item">
                    <h3><?php echo $paymentProfile['credit_card']['cardNumber']; ?></h3>
                    <address>
                        <?php if (!empty($paymentProfile['billing']['firstName'])): ?>
                            <?php echo $paymentProfile['billing']['firstName'] . ' '; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['lastName'])): ?>
                            <?php echo $paymentProfile['billing']['lastName']; ?>
                        <?php endif; ?><br/>
                        <?php if (!empty($paymentProfile['billing']['company'])): ?>
                            <?php echo $paymentProfile['billing']['company'] . '<br/>'; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['address'])): ?>
                            <?php echo $paymentProfile['billing']['address'] . '<br/>'; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['city'])): ?>
                            <?php echo $paymentProfile['billing']['city'] . ','; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['state'])): ?>
                            <?php echo $paymentProfile['billing']['state'] . ','; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['zip'])): ?>
                            <?php echo $paymentProfile['billing']['zip']; ?>
                        <?php endif; ?><br/>
                        <?php if (!empty($paymentProfile['billing']['country'])): ?>
                            <?php echo $paymentProfile['billing']['country'] . '<br/>'; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['phoneNumber'])): ?>
                            <?php echo 'T: ' . $paymentProfile['billing']['phoneNumber']; ?>
                        <?php endif; ?>
                        <?php if (!empty($paymentProfile['billing']['faxNumber'])): ?>
                            <?php echo '<br/>F: ' . $paymentProfile['billing']['faxNumber']; ?>
                        <?php endif; ?>
                    </address>
                    <p><a class="link-remove" href="#" onclick="deleteCard('<?php echo $id; ?>');"><?php echo $this->__('Delete Card'); ?></a></p>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
</div>
<script type="text/javascript">
    function deleteCard(cardId) {
        if (confirm('<?php echo $this->__('Are you sure you want to delete this card?'); ?>')) {
            window.location = '<?php echo $this->getDeleteAction() . 'id/'; ?>' + cardId;
        }
        return false;
    }
</script>