<?php
/**
 * @var Goodahead_Authorizenet_Block_Account_Create $this
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Your Authorize.net Cards'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getSaveAction(); ?>" method="post" id="form-validate">
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="profile[customer_type]" value="individual"/>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Card Information'); ?></h2>
        <ul class="form-list sp-methods">
            <li>
                <label class="required" for="goodahead_authorizenet_cc_type"><em>*</em><?php echo $this->__('Credit Card Type'); ?></label>
                <div class="input-box">
                    <select class="required-entry validate-cc-type-select" name="profile[cc_type]" id="goodahead_authorizenet_cc_type" autocomplete="off">
                        <option value=""><?php echo $this->__('--Please Select--'); ?></option>
                        <?php foreach ($this->getCcAvailableTypes() as $typeCode => $typeName): ?>
                            <option value="<?php echo $typeCode; ?>"><?php echo $typeName; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </li>
            <li>
                <label class="required" for="goodahead_authorizenet_cc_number"><em>*</em><?php echo $this->__('Credit Card Number'); ?></label>
                <div class="input-box">
                    <input type="text" value="" class="input-text validate-cc-number validate-cc-type" title="Credit Card Number" name="profile[cc_number]" id="goodahead_authorizenet_cc_number" autocomplete="off">
                </div>
            </li>
            <li id="goodahead_authorizenet_cc_type_exp_div">
                <label class="required" for="goodahead_authorizenet_expiration"><em>*</em><?php echo $this->__('Expiration Date'); ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select class="month validate-cc-exp required-entry" name="profile[cc_exp_month]" id="goodahead_authorizenet_expiration" autocomplete="off">
                            <option selected="selected" value=""><?php echo $this->__('Month'); ?></option>
                            <option value="1"><?php echo $this->__('01 - January'); ?></option>
                            <option value="2"><?php echo $this->__('02 - February'); ?></option>
                            <option value="3"><?php echo $this->__('03 - March'); ?></option>
                            <option value="4"><?php echo $this->__('04 - April'); ?></option>
                            <option value="5"><?php echo $this->__('05 - May'); ?></option>
                            <option value="6"><?php echo $this->__('06 - June'); ?></option>
                            <option value="7"><?php echo $this->__('07 - July'); ?></option>
                            <option value="8"><?php echo $this->__('08 - August'); ?></option>
                            <option value="9"><?php echo $this->__('09 - September'); ?></option>
                            <option value="10"><?php echo $this->__('10 - October'); ?></option>
                            <option value="11"><?php echo $this->__('11 - November'); ?></option>
                            <option value="12"><?php echo $this->__('12 - December'); ?></option>
                        </select>
                    </div>
                    <div class="v-fix">
                        <select class="year required-entry" name="profile[cc_exp_year]" id="goodahead_authorizenet_expiration_yr" autocomplete="off">
                            <option selected="selected" value=""><?php echo $this->__('Year'); ?></option>
                            <option value="2010"><?php echo $this->__('2010'); ?></option>
                            <option value="2011"><?php echo $this->__('2011'); ?></option>
                            <option value="2012"><?php echo $this->__('2012'); ?></option>
                            <option value="2013"><?php echo $this->__('2013'); ?></option>
                            <option value="2014"><?php echo $this->__('2014'); ?></option>
                            <option value="2015"><?php echo $this->__('2015'); ?></option>
                            <option value="2016"><?php echo $this->__('2016'); ?></option>
                            <option value="2017"><?php echo $this->__('2017'); ?></option>
                            <option value="2018"><?php echo $this->__('2018'); ?></option>
                            <option value="2019"><?php echo $this->__('2019'); ?></option>
                            <option value="2020"><?php echo $this->__('2020'); ?></option>
                        </select>
                    </div>
                </div>
            </li>
            <?php if ($this->hasVerification()): ?>
            <li id="goodahead_authorizenet_cc_type_cvv_div">
                <label class="required" for="goodahead_authorizenet_cc_cid"><em>*</em><?php echo $this->__('Card Verification Number'); ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" value="" name="profile[cc_cid]" id="goodahead_authorizenet_cc_cid" class="input-text cvv required-entry validate-cc-cvn" title="Card Verification Number" autocomplete="off">
                    </div>
                </div>
            </li>
            <?php endif; ?>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Billing Address'); ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="firstname"><?php echo  $this->__('Firstname'); ?></label>
                    <div class="input-box">
                        <input type="text" id="firstname" class="input-text" title="<?php echo  $this->__('Firstname'); ?>" name="profile[firstname]"/>
                    </div>
                </div>
                <div class="field">
                    <label for="lastname"><?php echo  $this->__('Lastname'); ?></label>
                    <div class="input-box">
                        <input type="text" id="lastname" class="input-text" title="<?php echo  $this->__('Lastname'); ?>" name="profile[lastname]"/>
                    </div>
                </div>
            </li>
            <li class="wide">
                <label for="company"><?php echo  $this->__('Company'); ?></label>
                <div class="input-box">
                    <input type="text" id="company" class="input-text" title="<?php echo  $this->__('Company'); ?>" name="profile[company]"/>
                </div>
            </li>
            <li class="wide">
                <label for="address"><?php echo  $this->__('Address'); ?></label>
                <div class="input-box">
                    <input type="text" id="address" class="input-text" title="<?php echo  $this->__('Address'); ?>" name="profile[address]"/>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="city"><?php echo  $this->__('City'); ?></label>
                    <div class="input-box">
                        <input type="text" id="city" class="input-text" title="<?php echo  $this->__('City'); ?>" name="profile[city]"/>
                    </div>
                </div>
                <div class="field">
                    <label for="state"><?php echo  $this->__('State'); ?></label>
                    <div class="input-box">
                        <input type="text" id="state" class="input-text" title="<?php echo  $this->__('State'); ?>" name="profile[state]"/>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="zip"><?php echo  $this->__('Zip'); ?></label>
                    <div class="input-box">
                        <input type="text" id="zip" class="input-text" title="<?php echo  $this->__('Zip'); ?>" name="profile[zip]"/>
                    </div>
                </div>
                <div class="field">
                    <label for="country"><?php echo  $this->__('Country'); ?></label>
                    <div class="input-box">
                        <input type="text" id="country" class="input-text" title="<?php echo  $this->__('Country'); ?>" name="profile[country]"/>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="phone"><?php echo  $this->__('Phone Number'); ?></label>
                    <div class="input-box">
                        <input type="text" id="phone" class="input-text" title="<?php echo  $this->__('Phone Number'); ?>" name="profile[phone]"/>
                    </div>
                </div>
                <div class="field">
                    <label for="fax"><?php echo  $this->__('Fax Number'); ?></label>
                    <div class="input-box">
                        <input type="text" id="fax" class="input-text" title="<?php echo  $this->__('Fax Number'); ?>" name="profile[fax]"/>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>