<div id="block_notice_wizard_welcome_description" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php $tempString = Mage::helper('M2ePro')->__('<strong>You have successfully upgraded M2E Pro to v. %ver%.</strong><br/><br/>
    In the table below there are recommended server settings, which guaranty stable working of the extension. <br/><br/>
    Please, compare the setting with yours.
    <br/><br/>
    Press the <span style="text-decoration: underline;">Start Configuration</span> button to start setting M2E Pro configuration.');
    echo str_replace('%ver%',$this->version,$tempString); ?>
</div>